#! /usr/bin/env bash

# shell script used to combine data scraping and wrangling

# scrape and wrangle all CA weather data into a csv
# fields: station_id, date, wthr_dtype, wthr_val
./ca_wthr_scraper -r 2016 2020

# aggregate data by county, year, and month
./wthr_filter.py

rm 2016_2020_ca_wthr.csv



